CREATE TABLE public.career_positions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT NOT NULL UNIQUE,
 name_vi TEXT NOT NULL, name_en TEXT NOT NULL, category TEXT NOT NULL CHECK(category IN ('software','data_ai','security','infrastructure','quality','product')),
 description TEXT NOT NULL DEFAULT '', skills TEXT[] NOT NULL DEFAULT '{}', search_text TEXT NOT NULL,
 version UUID NOT NULL DEFAULT gen_random_uuid(), deleted_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX career_positions_names ON public.career_positions(lower(name_vi),lower(name_en)) WHERE deleted_at IS NULL;
ALTER TABLE public.student_profiles ADD COLUMN career_position_id UUID REFERENCES public.career_positions(id);
CREATE INDEX student_profiles_career_position ON public.student_profiles(career_position_id);
ALTER TABLE public.career_positions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.career_positions FROM PUBLIC;
DO $$ DECLARE r TEXT; BEGIN
 FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN EXECUTE format('REVOKE ALL ON public.career_positions FROM %I',r); END IF;
 END LOOP;
END $$;
-- Initial catalog is inserted once by this migration; deleted entries are not recreated on startup.
INSERT INTO public.career_positions(code,name_vi,name_en,category,description,skills,search_text) VALUES
('frontend','Lập trình viên giao diện web','Frontend Developer','software','Xây dựng giao diện web, khả năng tương tác và trải nghiệm trên trình duyệt.',ARRAY['HTML/CSS','JavaScript/TypeScript','React','Accessibility'],'frontend lap trinh vien giao dien web frontend developer xay dung giao dien web, kha nang tuong tac va trai nghiem tren trinh duyet. html/css javascript/typescript react accessibility'),
('backend','Lập trình viên phía máy chủ','Backend Developer','software','Phát triển API, xử lý nghiệp vụ và truy cập dữ liệu phía máy chủ.',ARRAY['Node.js/Java/.NET','SQL','REST API','Bảo mật ứng dụng'],'backend lap trinh vien phia may chu backend developer phat trien api, xu ly nghiep vu va truy cap du lieu phia may chu. node.js/java/.net sql rest api bao mat ung dung'),
('fullstack','Lập trình viên toàn diện','Full-stack Developer','software','Phát triển cả giao diện và dịch vụ phía máy chủ của ứng dụng web.',ARRAY['Frontend','Backend','SQL','Git'],'fullstack lap trinh vien toan dien full-stack developer phat trien ca giao dien va dich vu phia may chu cua ung dung web. frontend backend sql git'),
('mobile','Lập trình viên ứng dụng di động','Mobile Developer','software','Xây dựng và bảo trì ứng dụng trên thiết bị di động.',ARRAY['Kotlin/Swift','Flutter/React Native','Mobile UI','API'],'mobile lap trinh vien ung dung di dong mobile developer xay dung va bao tri ung dung tren thiet bi di dong. kotlin/swift flutter/react native mobile ui api'),
('game','Lập trình viên trò chơi','Game Developer','software','Lập trình cơ chế chơi, tương tác và hiệu năng trò chơi.',ARRAY['C#/C++','Unity/Unreal','Toán ứng dụng','Tối ưu hiệu năng'],'game lap trinh vien tro choi game developer lap trinh co che choi, tuong tac va hieu nang tro choi. c#/c++ unity/unreal toan ung dung toi uu hieu nang'),
('software','Kỹ sư phần mềm','Software Engineer','software','Thiết kế, triển khai và bảo trì phần mềm theo yêu cầu nghiệp vụ.',ARRAY['Cấu trúc dữ liệu','Thiết kế phần mềm','Kiểm thử','Git'],'software ky su phan mem software engineer thiet ke, trien khai va bao tri phan mem theo yeu cau nghiep vu. cau truc du lieu thiet ke phan mem kiem thu git'),
('data-engineer','Kỹ sư dữ liệu','Data Engineer','data_ai','Xây dựng luồng thu thập, xử lý và lưu trữ dữ liệu.',ARRAY['SQL','Python','ETL/ELT','Data warehouse'],'data-engineer ky su du lieu data engineer xay dung luong thu thap, xu ly va luu tru du lieu. sql python etl/elt data warehouse'),
('data-analyst','Chuyên viên phân tích dữ liệu','Data Analyst','data_ai','Phân tích dữ liệu và xây dựng báo cáo hỗ trợ quyết định.',ARRAY['SQL','Thống kê','Power BI/Tableau','Trực quan hóa dữ liệu'],'data-analyst chuyen vien phan tich du lieu data analyst phan tich du lieu va xay dung bao cao ho tro quyet dinh. sql thong ke power bi/tableau truc quan hoa du lieu'),
('data-scientist','Nhà khoa học dữ liệu','Data Scientist','data_ai','Phân tích và mô hình hóa dữ liệu để giải quyết bài toán thực tế.',ARRAY['Python','Thống kê','Machine learning','Thực nghiệm'],'data-scientist nha khoa hoc du lieu data scientist phan tich va mo hinh hoa du lieu de giai quyet bai toan thuc te. python thong ke machine learning thuc nghiem'),
('ml-engineer','Kỹ sư học máy','Machine Learning Engineer','data_ai','Huấn luyện, triển khai và theo dõi mô hình học máy.',ARRAY['Python','Machine learning','MLOps','Đánh giá mô hình'],'ml-engineer ky su hoc may machine learning engineer huan luyen, trien khai va theo doi mo hinh hoc may. python machine learning mlops danh gia mo hinh'),
('ai-engineer','Kỹ sư trí tuệ nhân tạo','AI Engineer','data_ai','Tích hợp các mô hình AI vào ứng dụng và dịch vụ.',ARRAY['Python','Deep learning','LLM/NLP','API'],'ai-engineer ky su tri tue nhan tao ai engineer tich hop cac mo hinh ai vao ung dung va dich vu. python deep learning llm/nlp api'),
('security-analyst','Chuyên viên phân tích an toàn thông tin','Cybersecurity Analyst','security','Theo dõi, phân tích sự kiện và hỗ trợ xử lý sự cố an toàn thông tin.',ARRAY['Mạng máy tính','SIEM','Phân tích log','Ứng phó sự cố'],'security-analyst chuyen vien phan tich an toan thong tin cybersecurity analyst theo doi, phan tich su kien va ho tro xu ly su co an toan thong tin. mang may tinh siem phan tich log ung pho su co'),
('pentester','Chuyên viên kiểm thử xâm nhập','Penetration Tester','security','Đánh giá điểm yếu bảo mật của hệ thống trong phạm vi được cho phép.',ARRAY['Web security','Linux','Mạng máy tính','Báo cáo lỗ hổng'],'pentester chuyen vien kiem thu xam nhap penetration tester danh gia diem yeu bao mat cua he thong trong pham vi duoc cho phep. web security linux mang may tinh bao cao lo hong'),
('devops','Kỹ sư DevOps','DevOps Engineer','infrastructure','Tự động hóa xây dựng, triển khai và vận hành phần mềm.',ARRAY['CI/CD','Docker','Linux','Infrastructure as Code'],'devops ky su devops devops engineer tu dong hoa xay dung, trien khai va van hanh phan mem. ci/cd docker linux infrastructure as code'),
('cloud','Kỹ sư điện toán đám mây','Cloud Engineer','infrastructure','Triển khai, vận hành và tối ưu hệ thống trên nền tảng đám mây.',ARRAY['Cloud platform','Mạng','IAM','Giám sát hệ thống'],'cloud ky su dien toan dam may cloud engineer trien khai, van hanh va toi uu he thong tren nen tang dam may. cloud platform mang iam giam sat he thong'),
('network','Kỹ sư mạng','Network Engineer','infrastructure','Thiết kế, cấu hình và xử lý sự cố hạ tầng mạng.',ARRAY['TCP/IP','Routing/Switching','Firewall','Network monitoring'],'network ky su mang network engineer thiet ke, cau hinh va xu ly su co ha tang mang. tcp/ip routing/switching firewall network monitoring'),
('sysadmin','Quản trị viên hệ thống','System Administrator','infrastructure','Quản trị máy chủ, tài khoản, sao lưu và dịch vụ hạ tầng.',ARRAY['Linux/Windows Server','Scripting','Backup','Monitoring'],'sysadmin quan tri vien he thong system administrator quan tri may chu, tai khoan, sao luu va dich vu ha tang. linux/windows server scripting backup monitoring'),
('qa','Kỹ sư kiểm thử phần mềm','QA/Test Engineer','quality','Thiết kế kịch bản, thực hiện kiểm thử và tự động hóa kiểm tra chất lượng.',ARRAY['Test design','API testing','Playwright/Selenium','Quản lý lỗi'],'qa ky su kiem thu phan mem qa/test engineer thiet ke kich ban, thuc hien kiem thu va tu dong hoa kiem tra chat luong. test design api testing playwright/selenium quan ly loi'),
('business-analyst','Chuyên viên phân tích nghiệp vụ CNTT','IT Business Analyst','product','Thu thập, phân tích và diễn đạt yêu cầu nghiệp vụ cho đội phát triển.',ARRAY['Phân tích yêu cầu','UML/BPMN','Viết tài liệu','Giao tiếp'],'business-analyst chuyen vien phan tich nghiep vu cntt it business analyst thu thap, phan tich va dien dat yeu cau nghiep vu cho doi phat trien. phan tich yeu cau uml/bpmn viet tai lieu giao tiep'),
('ux-ui','Nhà thiết kế trải nghiệm và giao diện','UX/UI Designer','product','Nghiên cứu nhu cầu người dùng, thiết kế luồng tương tác và giao diện số.',ARRAY['User research','Figma','Prototyping','Accessibility'],'ux-ui nha thiet ke trai nghiem va giao dien ux/ui designer nghien cuu nhu cau nguoi dung, thiet ke luong tuong tac va giao dien so. user research figma prototyping accessibility');
